### ISSUE TITLE
Feature request: i18n

### ISSUE THREAD

**Issue by arnaud** [murilo-campaner/react-native-credit-card-form-ui#1]
👋 Hi there.

Nice and polished library you've created here, kudos!

One feature I think it's currently lacking is the ability to internationalize texts.
That's in my opinion the main thing that will prevent someone like myself from relying on it on future projects.
I'd also stay with english localization as defaults.

What do you think?

**Comment by murilo-campaner** [comment]
Hello @arnaud 

This is a great suggestion! 

If you have the time and can develop this feature, it would be great! 
Otherwise, as soon as we have some time here we will arrange for the development of this functionality! 👍

**Comment by murilo-campaner** [comment]
I just saw that @robert already sent a PR #2  solving this and adding the prop "labels".

This property can now be informed, changing the field labels.

It is not standardized in English, but for now I think it solves. We can reopen in the future if applicable =)
